# Generated by Django 3.2.9 on 2021-11-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station_name', models.CharField(max_length=100)),
                ('member_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('constituency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.constituency')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.region')),
                ('tag', models.ManyToManyField(to='vote.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.region'),
        ),
    ]
