# Generated by Django 3.2.9 on 2021-12-21 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='constituency_code',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='pollingstation_code',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='region',
            name='region_code',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='PoliticalPartyR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.region')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalPartyPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalPartyC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('constituency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.constituency')),
            ],
        ),
    ]
