# Generated by Django 3.2.9 on 2021-12-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20211221_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoliticalPartyC',
            new_name='PoliticalPartyCStats',
        ),
        migrations.RenameModel(
            old_name='PoliticalPartyPS',
            new_name='PoliticalPartyPSStats',
        ),
        migrations.RenameModel(
            old_name='PoliticalPartyR',
            new_name='PoliticalPartyRStats',
        ),
    ]
