# Generated by Django 3.2.9 on 2021-11-30 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrations',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('consituenc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.constituency')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.politicalparty')),
                ('pollingstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.pollingstation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.region')),
            ],
        ),
        migrations.CreateModel(
            name='EcOfficial',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('consituenc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.constituency')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.politicalparty')),
                ('pollingstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.pollingstation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.region')),
            ],
        ),
    ]
