# Generated by Django 3.2.9 on 2021-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_remove_ecofficial_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecofficial',
            name='user_code',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='userregistrations',
            name='user_code',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
