# Generated by Django 3.2.9 on 2021-12-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20211221_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecofficial',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userregistrations',
            name='id',
        ),
    ]
